export const SEARCHING_DATA = "SEARCHING_DATA";

export const START_SEARCHING_DATA = "START_SEARCHING_DATA";
export const STOP_SEARCHING_DATA = "STOP_SEARCHING_DATA";
export const SEARCHING_DATA_SUCCESS = "SEARCHING_DATA_SUCCESS";
export const SEARCHING_DATA_FAILED = "SEARCHING_DATA_FAILED";
