export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";

export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAILED = "ADD_ITEM_TO_CART_FAILED";
export const START_ADD_ITEM_TO_CART = "START_ADD_ITEM_TO_CART";
export const STOP_ADD_ITEM_TO_CART = "STOP_ADD_ITEM_TO_CART";

export const SUBMIT_TO_PAYMENT = "SUBMIT_TO_PAYMENT";
export const BUY_NOW = "BUY_NOW";

export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const CHANGE_QTY_ITEM = "CHANGE_QTY_ITEM";

//confirm order
export const CONFIRM_ORDER = "CONFIRM_ORDER";
